management:
  context-path: /manage
  port: ${SERVER_PORT}
  

database:
  packagesToScan: com.hackday.mygrocery.service.daos.models
  hikari:
    dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    maximumPoolSize: 5
    maxLifetime: 30000
    idleTimeout: 30000
    autoCommit: false
    dataSourceProperties:
      url: jdbc:mysql://localhost:3306/mygrocery
      user: root
      password:
      prepStmtCacheSize: 256
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      cachePrepStmts: true
  # // http://blog.jhades.org/performance-tuning-of-spring-hibernate-applications/
  hibernateProperties:
    hibernate.jdbc.batch_size: 10
    hibernate.order_inserts: true
    hibernate.order_updates: true
    hibernate.generate_statistics: true
    hibernate.use_sql_comments: true


  
logging:
  level:
    com.ekart.springbootjetty.sample: DEBUG
